version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      root-production-dependencies:
        dependency-type: production
        update-types: [minor, patch]
  - package-ecosystem: npm
    directory: /backend
    schedule:
      interval: weekly
    groups:
      backend-production-dependencies:
        dependency-type: production
        update-types: [minor, patch]
  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: weekly
    groups:
      frontend-production-dependencies:
        dependency-type: production
        update-types: [minor, patch]
  - package-ecosystem: docker
    directory: /backend
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /frontend
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
